version: "2.1"
services:
  redis-qr:
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  qr-login-handler:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    expose:
      - "8080"
    links:
      - "redis-qr:database"
    depends_on:
      redis-qr:
        condition: service_healthy



